### ISSUE TITLE
Show version numbers for updated aurelia modules

### ISSUE THREAD

**Issue by adriatic** [SpoonX/aurelia-update#1]
At the moment, this tool displays:

```
> Starting update.
- aurelia-templating: Success!
- aurelia-metadata: Success!
- aurelia-http-client: Success!
- aurelia-framework: Success!
- aurelia-bootstrapper: Success!
- aurelia-binding: Success!
> Finished.
```

You may add a -v (for verbose) flag that would also show the current and updated version for each updated component

**Comment by RWOverdijk** [comment]
@adriatic That would be fantastic. Thing is, the command I'm running from doesn't return that currently.

Quick tip, just use git diff package.json :)
