### ISSUE TITLE
Update of aurelia-templating-router failed

### ISSUE THREAD

**Issue by schatekar** [SpoonX/aurelia-update#5]
Update of `aurelia-templating-router` failed on my machine with error `EPERM: operation not permitted, lstat`

Not sure if this is an issue with my setup but I felt it is worth reporting here.

**Comment by schatekar** [comment]
Running `aurelia-update` one more time upgraded `aurelia-templating-router` smoothly. So not sure if this is really an issue.

**Comment by RWOverdijk** [comment]
It's probably an issue on your system. I think you might have used sudo before, or used a different user. This is a permission problem.
