### ISSUE TITLE
Update broke my app

### ISSUE THREAD

**Issue by arnonuem** [SpoonX/aurelia-update#7]
After using aurelia-update my app was broken.
I had to manually install 'aurelia-pal-browser' to fix it again.

Could you please consider 'aurelia-pal-browser'?

Maybe install it when it is missing.

**Comment by RWOverdijk** [comment]
@arnonuem I don't understand what you mean. It doesn't _add_ dependencies, it just updates what exists.

**Comment by arnonuem** [comment]
If you want to simulate what i have done just follow these steps:
- clone https://github.com/Vheissu/aurelia-react-example
- run it to check that everything works as expected
- install your aurelia-update
- run aurelia-update
- run the app again and see that it is not running
- install aurelia-pal-browser
- run again -> everything works as expected again

I like the idea of having a generic update mechanism like you provide it.
All i am saying is that it needs to be more robust :)

**Comment by RWOverdijk** [comment]
@arnonuem I get it :) I built this back when versions changed 50 times a day. I never expected people to use it, and now they do haha.

I think the reason it fails, is because this updates. So the versions in that example might be outdated. It doesn't add dependencies.

**Comment by arnonuem** [comment]
Actually,

i just read the aurelia docs (http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/16) again and found the following at the end of the document (Updating Multiple Libraries):

```
"scripts": {
    "au-update": "npm install aurelia-binding@latest aurelia-bootstrapper@latest ...
    }
```

This means Aurelia provides an own way to update its stuff. 
If you have spare time you could migrate your tool to a script just doing that. 

That would be nice ;)

**Comment by RWOverdijk** [comment]
@arnonuem The tool was built for jspm, so if it sees you use cli, it could indeed do that. I'll link to it in the readme :) If you want to give it a go to detect what's being used and call it automatically, that would be awesome!

Closing this issue for now. Thanks for the info :)
